### ISSUE TITLE
Installation of ADORE

### ISSUE THREAD

**Issue by anas-abulehia** [eclipse-adore/adore_ROS1#15]
Hello All, 

I am trying to install and run ADORE ROS on my virtual machine. I have followed the instructions given in Quick start. However when I run `git clone --recurse-submodules -j8 git@github.com:eclipse/adore.git` I get the following error 

![image](https://user-images.githubusercontent.com/49106882/187089761-4ecde636-f8a9-4097-a1ec-6f4e8a5eb556.png)

I have cloned it manually from github and followed the instrunctions and run `make` the result appears 

![image](https://user-images.githubusercontent.com/49106882/187089844-a5426ea5-82f2-42dc-8233-3dfd4e7e94a1.png). 

Did I follow the instructions correctly ? where can we overcome this error. 

Regards, 
V

**Comment by daniel-gitgit** [comment]
Hi there,
thanks for contacting us. Did you register your ssh key with your github account? (https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)
Currently our instructions assume that the user has a github account with working keys. 
It is possible to check out anonymously by reconfiguring git to map from ssh to https in your git config, a short help article / note on that is coming up.
I'm going to post the link to the help article below as soon as the article is online.
Best regards
Daniel

**Comment by anas-abulehia** [comment]
I figure it out thanks,

**Comment by anas-abulehia** [comment]
I am trying to install ADORe in an Ubuntu Virtual Machine, it does not work, it says the Docker Does not work ? 
have you used ADORe in a virtual machine in Orcale VM

Regards,

**Comment by anas-abulehia** [comment]
![Screenshot from 2022-08-31 00-26-17](https://user-images.githubusercontent.com/49106882/187554510-031a6f3b-b37b-4b21-80b0-74cd3512a484.png)

**Comment by tlobig** [comment]
this is a docker issue, you need to add your user to the docker group.

**Comment by akoerner1** [comment]
@anas-abulehia You can run:
```bash
sudo usermod -a -G docker "${USER}"
```
to add yourself to the docker group.  Please note that you will need to log out of your user and log back in for the changes to take effect.  

Let me know if you have any other issues. Also I recommend checking out out branch dev_v0.3.1 with:
```bash
git checkout dev_v0.3.1
git submodule update --init --recursive
```
