### ISSUE TITLE
More details in README.md please

### ISSUE THREAD

**Issue by mfgpcm** [eclipse-adore/adore_ROS1#20]
It would be great if the README.md would mention that ADORe contains the entire cause-effect chain of automated driving, including perception and behaviour planning etc.

**Comment by daniel-gitgit** [comment]
Thanks for your comment, Peter! The perception layer is currently not in the scope of ADORe. We are trying to hold true to our mission, which is limited to "decision making, planning, control and simulation of automated vehicles". 

Simulation is only covered to a limited extend as DLR-TS is already providing a great simulation tool (https://github.com/eclipse/sumo). ADORe adds modules for simple vehicle dynamics, sensor range limitation (v2x, object detection), basic localization effects and beyond that refers to SUMO and CARLA for simulation. 

Regarding behavior planning, ADORe currently provides a feedback controller for the stabilization layer. Multiple trajectory planners using qpOASES for planning of different behaviors on the tactical level are given. A decision making module allows to control switching between tactical plans. A navigation module provides lane-level navigation information for the considered lane-network.
A concept called "View" is employed to provide environment data abstraction to the planning algorithms. Several view-providing modules exist for e.g. lane-following and lane-changing tasks. We consider the views to be on the behavior side of the interface between perception and behavior.
