### ISSUE TITLE
Create documentation: Subfolder structure

### ISSUE THREAD

**Issue by daniel-gitgit** [eclipse-adore/adore_ROS1#31]
Andrew: 

https://github.com/eclipse/adore/blob/dev_v0.3.2_doc/documentation/technical_documentation/system_and_development/subfolder_structure.md

- describe structure of modules
- Files Folder, docker folder, external etc.

**Comment by akoerner1** [comment]
Addressed in PR: https://github.com/eclipse/adore/pull/61
