### ISSUE TITLE
CLI for vehicle platform

### ISSUE THREAD

**Issue by daniel-gitgit** [eclipse-adore/adore_ROS1#50]
Andrew?

In our test vehicle the ros master is not located on the local machine. 

- create make-target "vcli", which starts adore-cli with a setup for a remote master:
  - do not start "roscore"
  - configure ROS to connect to remote master http://wiki.ros.org/ROS/Tutorials/MultipleMachines
  - ideally find a way to save ROS master ip persistently and in a way that doesn't confuse git

https://github.com/eclipse/adore/tree/dev_v0.3.2_bs

**Comment by daniel-gitgit** [comment]
given branch is intended for build system dev

**Comment by akoerner1** [comment]
Just a comment to characterize the issue and a possible solution with some facts:
- In the docker-compose.yaml the ros-master service is currently described as a sperate service
- With docker compose >v3, which we are using `docker swarm` can be used
- Using docker swarm hostnames for each service can be defined in the docker-compose files
- A new section needs to be added to the docker-compose file called `deploy:`

**Comment by daniel-gitgit** [comment]
Sounds great. Unfortunately, the ROS master in the car is not under our control. The pc running the ROS master is not using compose >v3 and it is starting the ROS master in a different manner.

**Comment by akoerner1** [comment]
> * ing docker swarm host names for each service can be defined in the docker-compose files
> * A new section needs to be add

Its simple then, we need a different docker compose file for the vehicle that excludes the rosmaster service and changes the environment variables for the ros master in the adore cli service.

With https://github.com/eclipse/adore/pull/52 I have made this process easier by splitting the adore cli services into their own distinct docker compose file [adore-cli.yaml](https://github.com/eclipse/adore/pull/52/files#diff-751e7463be7a56f60254c26885efaab731c0ea7b37fbe545297b5d8192c79a50).

I have added a recommended change as a comment here: https://github.com/eclipse/adore/pull/52/files#r1037083544

**Comment by tlobig** [comment]
got fixed in the car-repo (sorry this is not public)
