### ISSUE TITLE
error when running "make cli"

### ISSUE THREAD

**Issue by tk-menot** [eclipse-adore/adore_ROS1#64]
When running make cli, I encountered the following error message. I am using Ubuntu 20 and the Docker version is correct.
![image](https://github.com/eclipse/adore/assets/72853206/bd4d19a5-9c33-4f9b-b29c-a2a039dd4a7f)
Can anyone help me solve this problem? Thank you.

**Comment by akoerner1** [comment]
@tk-menot Can you try updating apt-cacher-ng?
```
cd adore/apt_cacher_ng_docker
git checkout master
git pull
```

**Comment by tk-menot** [comment]
It works, thank you.
